name : test workflow

on:
  push:
    branches: [ main ]
  
jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name : Echo massage
        run: echo "Github Action is Working sucessfully"